---
- name: Converge
  hosts: all
  gather_facts: true
  vars_files:
    - "vars/debian.yml"
    - "vars/redhat.yml"

  pre_tasks:
    - name: Install curl and gnupg [Debian]
      ansible.builtin.apt:
        pkg: ['curl', 'gnupg']
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: Download opentofu asc repo key [Debian]
      ansible.builtin.get_url:
        url: https://packages.opentofu.org/opentofu/tofu/gpgkey
        dest: /tmp/opentofu-repo.asc
        mode: '0644'
      when: ansible_os_family == "Debian"
    - name: Convert opentofu GPG key to binary format
      ansible.builtin.shell: "gpg --no-tty --batch --dearmor -o /tmp/opentofu-repo.gpg /tmp/opentofu-repo.asc >/dev/null"
      args:
        creates: /tmp/opentofu-repo.gpg
      when: ansible_os_family == "Debian"
  tasks:
    - name: Include os-specific vars (Ubuntu only)
      ansible.builtin.include_vars: "vars/ubuntu.yml"
      when: ansible_distribution == "Ubuntu"

    - name: Include willbrid.repo_installer
      ansible.builtin.include_role:
        name: "willbrid.repo_installer"
