---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    ri_redhat_dependencies_packages: ["ca-certificates"]
    ri_redhat_distro_repos:
      - name: epel
        description: EPEL YUM repo
        baseurl: https://dl.fedoraproject.org/pub/epel/$releasever/Everything/$basearch/
        is_external_repo: false
      - name: opentofu
        description: opentofu
        baseurl: https://packages.opentofu.org/opentofu/tofu/rpm_any/rpm_any/\$basearch
        is_external_repo: true
        enabled: true
        extra_options:
          repo_gpgcheck: 0
          gpgcheck: 1
          gpgkey: >
            https://get.opentofu.org/opentofu.gpg
            https://packages.opentofu.org/opentofu/tofu/gpgkey
          sslverify: 1
          sslcacert: /etc/pki/tls/certs/ca-bundle.crt
          metadata_expire: 300
    ri_debian_dependencies_packages: ["apt-transport-https", "ca-certificates", "curl", "gnupg"]
    ri_debian_distro_repos:
      - name: opentofu
        baseurl: https://packages.opentofu.org/opentofu/tofu/any/
        distribution: any
        components: ["main"]
        type: "deb"
        gpgkeys:
          - id: main
            url: https://get.opentofu.org/opentofu.gpg
            type: "gpg"
          - id: repo
            url: file:///tmp/opentofu-repo.gpg
            type: "gpg"
        is_external_repo: true
  pre_tasks:
    - name: Install curl [Debian]
      ansible.builtin.apt:
        pkg: ['curl', 'gnupg']
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: Download opentofu asc repo key and save in /tmp/opentofu-repo.gpg [Debian]
      ansible.builtin.shell: "curl -fsSL https://packages.opentofu.org/opentofu/tofu/gpgkey | gpg --no-tty --batch --dearmor -o /tmp/opentofu-repo.gpg >/dev/null"
      args:
        creates: /tmp/opentofu-repo.gpg
      when: ansible_os_family == "Debian"
  tasks:
    - name: Include willbrid.repo_installer
      ansible.builtin.include_role:
        name: "willbrid.repo_installer"
