---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Check RedHat distributions
      when: ansible_os_family == "RedHat"
      block:
        - name: Get epel repo info [RedHat]
          ansible.builtin.command: "dnf repoinfo epel"
          register: epel_repo_info
          changed_when: false
        - name: Get opentofu repo info [RedHat]
          ansible.builtin.command: "dnf repoinfo opentofu"
          register: opentofu_repo_info
          changed_when: false
        - name: Verify the presence of epel and opentofu repo [RedHat]
          ansible.builtin.assert:
            that:
              - epel_repo_info is defined and epel_repo_info.stdout_lines | select('match', '^Repo-id\\s+:\\s+epel$') | list | length > 0
              - opentofu_repo_info is defined and opentofu_repo_info.stdout_lines | select('match', '^Repo-id\\s+:\\s+opentofu$') | list | length > 0

    - name: Check Debian distributions
      when: ansible_os_family == "Debian"
      block:
        - name: Check if opentofu repo is present in APT sources [Debian]
          ansible.builtin.shell: grep -R 'packages.opentofu.org' /etc/apt/sources.list /etc/apt/sources.list.d/ || true
          register: ri_repo_debian_check
          changed_when: false
        - name: Assert that opentofu repo is found [Debian]
          ansible.builtin.assert:
            that:
              - ri_repo_debian_check.stdout != ''
        - name: Check if ppa:ondrej/php repo is present in APT sources [Debian]
          ansible.builtin.shell: grep -R 'ondrej/php' /etc/apt/sources.list /etc/apt/sources.list.d/ || true
          register: ri_repo_ubuntu_check
          changed_when: false
          when: ansible_distribution == "Ubuntu"
        - name: Assert that ppa:ondrej/php repo is found [Debian]
          ansible.builtin.assert:
            that:
              - ri_repo_ubuntu_check.stdout != ''
          when: ansible_distribution == "Ubuntu"
